<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>ADD</title>
</head>
<body>

	
			<h1>Product  Add</h1>



	<form action="index.php?c=product&a=save" method="POST">
		<table class="table-primary">
			<tr>
				<td>PRODUCT NAME</td>
				<td> <input type="text" name="product[name]"> </td>
			</tr>
			<tr>
				<td>COST</td>
				<td> <input type="text" name="product[cost]"> </td>
			</tr>
			<tr>
				<td>PRICE</td>
				<td> <input type="text" name="product[price]"> </td>
			</tr>
			<tr>
				<td>SKU</td>
				<td> <input type="text" name="product[sku]"> </td>
			</tr>
			<tr>		
				<td>STATUS</td>
				<td>
					<select name="product[status]">
						<option>SELECT BELOW</option>
						<option>ACTIVE</option>
						<option>INACTIVE</option>
					</select>

				</td>
			</tr>
		
			<tr>
				<td>DISCRIPTION</td>
				<td> <input type="text" name="product[description]"> </td>
			</tr>
			<tr>
				<td>COLOR</td>
				<td> <input type="text" name="product[color]"> </td>
			</tr>
			<tr>
				<td>MATERIAL</td>
				<td> <input type="text" name="product[material]"> </td>
			</tr>
			<tr>
				<th> <button> <a href="index.php?c=product&a=grid">CANCEL</a> </button></th>
				<th> <button type="submit"> SAVE </button></th>


			</tr>
	</table>
	</form>

</body>
</html>