<?php $products = $this->products;
?>


			 <?php require_once "View/html/head.phtml"; ?>
			 <?php require_once "View/html/header.phtml"; ?>
<body>
			
			 <button type="button" class="btn btn-dark"><a href="index.php?c=Product&a=add">ADD</a></button>

	
		<table class="table table-light">
 		 <thead>
   		 <tr>
		 <th scope="col">PRODUCT ID</th>
		 <th scope="col">PRODUCT NAME</th>
		 <th scope="col">COST</th>
		 <th scope="col">PRICE</th>
		 <th scope="col">SKU</th>
		 <th scope="col">STATUS</th>
		 <th scope="col">DISCRIPTION</th>
		 <th scope="col">COLOR</th>
		 <th scope="col">MATERIAL</th>
		 <th scope="col">CREATED AT</th>
		 <th scope="col">UPDATED AT</th>
		 <th scope="col">EDIT</th>
		 <th scope="col">DELETE</th>
		  </tr>
        </thead>

	<?php foreach ($products as $product): ?>
		<tr>
			<td><?php echo $product->product_id; ?></td>
			<td><?php echo $product->name; ?></td>
			<td><?php echo $product->cost; ?></td>
			<td><?php echo $product->price; ?></td>
			<td><?php echo $product->sku; ?></td>
			<td><?php echo $product->status; ?></td>
			<td><?php echo $product->description; ?></td>
			<td><?php echo $product->color; ?></td>
			<td><?php echo $product->material; ?></td>
			<td><?php echo $product->inserted_at; ?></td>
			<td><?php echo $product->updated_at; ?></td>
			<td> <a href="index.php?c=Product&a=edit&id=<?php echo $product->product_id; ?>">EDIT</a> </td>
			<td> <a href="index.php?c=Product&a=delete&id=<?php echo $product->product_id; ?>">DELETE</a> </td>
		</tr>
	<?php endforeach; ?>
	</table>

			 <?php require_once "View/html/footer.phtml"; ?>



</body>
</html>