<?php

$url = new Model_Core_Url();
$customer = $this->customer;

?>
<?php require_once "View/html/head.phtml"; ?>
    <?php require_once "View/html/header.phtml"; ?>

    <div class="content-main">
        <form action="index.php?c=customer&a=save" method="POST">

            

            <div class="contents">

            <table class="table table-light">
                <tr>
                    <td>
                        <h1>Add Customer</h1>
                    </td>
                    <td class="sub-head">
                        <a href="index.php?c=customer&a=grid">Cancel</a>
                        <button type="submit">Save</button>
                    </td>
                </tr>
            </table>



            <div class="content active">
            <table class="table table-light">

                
                <tr>
                    <td>First_name: </td>
                    <td><input type="text" name="customer[firstname]"></td>
                </tr>
                <tr>
                    <td>Last_name: </td>
                    <td><input type="text" name="customer[lastname]" ></td>
                </tr>
                <tr>
                    <td>Email: </td>
                    <td><input type="email" name="customer[email]"></td>
                </tr>
                <tr>
                    <td>Gender: </td>
                    <td>
                        <input type="radio" name="customer[gender]">Male <br>
                        <input type="radio" name="gender" >Female <br>

                    </td>
                </tr>
                <tr>
                    <td>Mobile: </td>
                    <td><input type="number" name="customer[mobile]" ></td>
                </tr>
                <tr>
                    <td>Status: </td>
                    <td>
                       <select name="customer[status]" > 
                        <option>SELECT BELOW</option>
                        <option>ACTIVE</option>
                        <option>INACTIVE</option>
                    </select>
                    </td>
                </tr>


            </table>
            <div>

            <div class="content">
            <table class="table table-light">

                <tr>
                    <th colspan="2"><h3>Address</h3></th>
                </tr>
                <tr>
                    <td>
                        Address:
                    </td>
                    <td><textarea name="address[address]"></textarea></td>

                </tr>
                <tr>
                    <td>city:</td>
                    <td><input type="text" name="address[city]" ></td>
                </tr>
                <tr>
                    <td>state:</td>
                    <td><input type="text" name="address[state]" ></td>
                </tr>
                <tr>
                    <td>country:</td>
                    <td><input type="text" name="address[country]"></td>
                </tr>
                <tr>
                    <td>zipcode:</td>
                    <td><input type="text" name="address[zipcode]" ></td>
                </tr>


            </table>
            <div>

        </form>
    </div>
</div>
   