<?php

$url = new Model_Core_Url();
$customer = $this->customer;
$billingAddress = $this->billingaddress;
$shippingAddress = $this->shipppingaddress;



?>
<?php require_once "View/html/head.phtml"; ?>
    <?php require_once "View/html/header.phtml"; ?>

    <div class="content-main">
        <form action="index.php?c=customer&a=save&id=<?php echo $customer->customer_id ?>" method="post">

            
            <div class="contents">

            <table class="table table-light">
                <tr>
                    <td>
                        <h1>Edit Customer</h1>
                    </td>
                    <td class="sub-head">
                        <a href="index.php?c=customer&a=grid">Cancel</a>
                        <button type="submit">Save</button>
                    </td>
                </tr>
            </table>



            <div class="content active">
            <table class="table table-light">

                
                <tr>
                    <td>First_name: </td>
                    <td><input type="text" name="customer[firstname]" value="<?php echo $customer->firstname;?>"></td>
                </tr>
                <tr>
                    <td>Last_name: </td>
                    <td><input type="text" name="customer[lastname]" value="<?php echo $customer->lastname;?>"></td>
                </tr>
                <tr>
                    <td>Email: </td>
                    <td><input type="email" name="customer[email]" value="<?php echo $customer->email;?>"></td>
                </tr>
                <tr>
                    <td>Gender: </td>
                    <td>
                        <input type="radio" name="customer[gender]" value="M" <?php if($customer->gender=='M'){echo"checked";}?>>Male <br>
                        <input type="radio" name="gender" value="F" <?php if($customer->gender=='F'){echo"checked";}?>>Female <br>

                    </td>
                </tr>
                <tr>
                    <td>Mobile: </td>
                    <td><input type="number" name="customer[mobile]" value="<?php echo $customer->mobile;?>"></td>
                </tr>
                <tr>
                    <td>Status: </td>
                    <td>
                       <select name="customer[status]" value="<?php echo $customer->status ?>"> 
                        <option>SELECT BELOW</option>
                        <option>ACTIVE</option>
                        <option>INACTIVE</option>
                    </select>
                    </td>
                </tr>


            </table>
            <div>

            <div class="content">
            <table class="table table-light">

                <tr>
                    <th colspan="2"><h3>Shipping Address</h3></th>
                </tr>
                <tr>
                    <td>
                        Address:
                    </td>
                    <td><textarea name="shippingAddress[address]"><?php echo $shippingAddress->address; ?></textarea></td>

                </tr>
                <tr>
                    <td>city:</td>
                    <td><input type="text" name="shippingAddress[city]" value="<?php echo $shippingAddress->city; ?>"></td>
                </tr>
                <tr>
                    <td>state:</td>
                    <td><input type="text" name="shippingAddress[state]" value="<?php echo $shippingAddress->state; ?>"></td>
                </tr>
                <tr>
                    <td>country:</td>
                    <td><input type="text" name="shippingAddress[country]" value="<?php echo $shippingAddress->country; ?>"></td>
                </tr>
                <tr>
                    <td>zipcode:</td>
                    <td><input type="text" name="shippingAddress[zipcode]" value="<?php echo $shippingAddress->zipcode; ?>"></td>
                </tr>


            </table>

            <table class="table table-light">

                <tr>
                    <th colspan="2"><h3>Billing Address</h3></th>
                </tr>
                <tr>
                    <td>
                        Address:
                    </td>
                    <td><textarea name="billingAddress[address]"><?php echo $billingAddress->address; ?></textarea></td>

                </tr>
                <tr>
                    <td>city:</td>
                    <td><input type="text" name="billingAddress[city]" value="<?php echo $billingAddress->city; ?>"></td>
                </tr>
                <tr>
                    <td>state:</td>
                    <td><input type="text" name="billingAddress[state]" value="<?php echo $billingAddress->state; ?>"></td>
                </tr>
                <tr>
                    <td>country:</td>
                    <td><input type="text" name="billingAddress[country]" value="<?php echo $billingAddress->country; ?>"></td>
                </tr>
                <tr>
                    <td>zipcode:</td>
                    <td><input type="text" name="billingAddress[zipcode]" value="<?php echo $billingAddress->zipcode; ?>"></td>
                </tr>


            </table>
            <div>

        </form>
    </div>
</div>
   