<?php

$url = new Model_Core_Url();
$salesman = $this->salesman;
$salesmanAddress = $this->address;



?>
<?php require_once "View/html/head.phtml"; ?>
    <?php require_once "View/html/header.phtml"; ?>

    <div class="content-main">
        <form action="index.php?c=salesman&a=save&id=<?php echo $salesman->salesman_id ?>" method="post">

            
            <div class="contents">

            <table class="table table-light">
                <tr>
                    <td>
                        <h1>Edit Salesman</h1>
                    </td>
                    <td class="sub-head">
                        <a href="index.php?c=salesman&a=grid">Cancel</a>
                        <button type="submit">Save</button>
                    </td>
                </tr>
            </table>



            <div class="content active">
            <table class="table table-light">

                
                <tr>
                    <td>First_name: </td>
                    <td><input type="text" name="salesman[firstname]" value="<?php echo $salesman->firstname;?>"></td>
                </tr>
                <tr>
                    <td>Last_name: </td>
                    <td><input type="text" name="salesman[lastname]" value="<?php echo $salesman->lastname;?>"></td>
                </tr>
                <tr>
                    <td>Email: </td>
                    <td><input type="email" name="salesman[email]" value="<?php echo $salesman->email;?>"></td>
                </tr>
                <tr>
                    <td>Gender: </td>
                    <td>
                        <input type="radio" name="salesman[gender]" value="M" <?php if($salesman->gender=='M'){echo"checked";}?>>Male <br>
                        <input type="radio" name="gender" value="F" <?php if($salesman->gender=='F'){echo"checked";}?>>Female <br>

                    </td>
                </tr>
                <tr>
                    <td>Mobile: </td>
                    <td><input type="number" name="salesman[mobile]" value="<?php echo $salesman->mobile;?>"></td>
                </tr>
                <tr>
                    <td>Status: </td>
                    <td>
                       <select name="salesman[status]" value="<?php echo $salesman->status ?>"> 
                        <option>SELECT BELOW</option>
                        <option>ACTIVE</option>
                        <option>INACTIVE</option>
                    </select>
                    </td>
                </tr>


            </table>
            <div>

            <div class="content">
            <table class="table table-light">

                <tr>
                    <th colspan="2"><h3> Salesman Address</h3></th>
                </tr>
                <tr>
                    <td>
                        Address:
                    </td>
                    <td><textarea name="address[address]"><?php echo $salesmanAddress->address; ?></textarea></td>

                </tr>
                <tr>
                    <td>city:</td>
                    <td><input type="text" name="address[city]" value="<?php echo $salesmanAddress->city; ?>"></td>
                </tr>
                <tr>
                    <td>state:</td>
                    <td><input type="text" name="address[state]" value="<?php echo $salesmanAddress->state; ?>"></td>
                </tr>
                <tr>
                    <td>country:</td>
                    <td><input type="text" name="address[country]" value="<?php echo $salesmanAddress->country; ?>"></td>
                </tr>
                <tr>
                    <td>zipcode:</td>
                    <td><input type="text" name="address[zipcode]" value="<?php echo $salesmanAddress->zipcode; ?>"></td>
                </tr>


            </table>
            <div>

        </form>
    </div>
</div>
   