<?php
$url=Ccc::getModel('Core_Url');

$salesmans = $this->salesmans;



?>
    <?php require_once "View/html/head.phtml"; ?>
    <?php require_once "View/html/header.phtml"; ?>

   <body>
       <h3> <p class="text-decoration-line-through">Manage Salesman Content.</p></h3>
      <button type="button" class="btn btn-dark"><a href="index.php?c=vendor&a=add">ADD</a></button>
            

        <table class="table table-light">
         <thead>
         <tr>
         <th scope="col">Salesman_id</th>
         <th scope="col">First_name</th>
         <th scope="col">Last_name</th>
         <th scope="col">Email</th>
         <th scope="col">Gender</th>
         <th scope="col">Mobile</th>
         <th scope="col">Status</th>
         <th scope="col">inserted_at</th>
         <th scope="col">updated_at</th>
         <th scope="col">Edit</th>
         <th scope="col">Delete</th>
         
          </tr>
        </thead>
               <?php
                //feching data to form from database
                foreach($salesmans as $row){

                ?>

                
                <tr>
                    <td><?php echo $row->salesman_id; ?></td>
                    <td><?php echo $row->firstname; ?></td>
                    <td><?php echo $row->lastname; ?></td>
                    <td><?php echo $row->mail; ?></td>
                    <td><?php echo $row->gender; ?></td>
                    <td><?php echo $row->no; ?></td>
                    <td><?php echo $row->status; ?></td>
                    <td><?php echo $row->inserted_at; ?></td>
                    <td><?php echo $row->updated_at; ?></td>
                    <td><a href="index.php?c=salesman&a=edit&id=<?php echo $row->salesman_id; ?>">edit</a></td>
                    <td><a href="index.php?c=salesman&a=delete&id=<?php echo $row->salesman_id; ?>">delete</a></td>
                </tr>
                <?php
                }
                ?>
            </table>
        <?php require_once "View/html/footer.phtml"; ?>



</body>
</html>
       