<?php
$rows = $this->getCollection();
// echo "<pre>";
// print_r($this);
// die();
// // // $pager = Ccc::getModel('Core_Pager');
$pager = $this->getPager();
// print_r($pager); 

?>
<div class="content">
	<table class="table table-light">
		<tr>
			<td><h3 align="left"><?php echo $this->getTitle(); ?></h3></td>
			<?php foreach ($this->getButtons() as $key => $button) : ?>
			<td><h3 align="right"><a href="<?php echo $button['url']; ?>"><?php echo $button['title']; ?></a></h3></td>
			<?php endforeach; ?>
		</tr>
	</table>
	<table class="table table-light">
		<?php if (!$rows): ?>
				No data found.
		<?php else: ?>
			<tr align="center">
			<?php foreach ($this->getColumns() as $key => $column) : ?>
				<th><?php echo $column['title']; ?></th>
			<?php endforeach; ?>

			<?php foreach ($this->getActions() as $key => $action) : ?>
				<th><?php echo $action['title']; ?></th>
			<?php endforeach; ?>
		</tr>

		<?php foreach ($rows as $row) : ?>
		<tr align="center">
			<?php foreach($this->getColumns() as $key => $column): ?>
				<td><?php echo $this->getColumnValue($row, $key); ?></td>
			<?php endforeach; ?>
			<?php foreach($this->getActions() as $key => $action): ?>
				<?php if ($action['title'] == 'Edit'):?>	
					<td><a href="<?php echo $this->getUrl($key , null,['id'=> $row->getId()],true)?>"><?php echo $action['title']?></a></td>
				<?php elseif ($action['title'] == 'Delete'): ?>
					<td><a href="<?php echo $this->getUrl($key , null,['id'=> $row->getId()],true)?>"><?php echo $action['title']?></a></td>		
				<?php endif; ?>	
			<?php endforeach; ?>
		</tr>
		<?php endforeach; ?>
		<?php endif; ?>
	</table>
	<table border="2px" width="100%">
		<tr>
		
	        <td><a  href="<?php echo $this->getUrl('grid',null,['p'=>$pager->start],true) ?>">Start</a></td>
	        <td><a  href="<?php echo $this->getUrl('grid',null,['p'=>$pager->previous],true) ?>" >Previous</a></td>
	        <td><a  href="<?php echo $this->getUrl('grid',null,['p'=>$pager->currentPage],true) ?>" ><?php echo $pager->currentPage;?></a></td>
	        <td><a  href="<?php echo $this->getUrl('grid',null,['p'=>$pager->next],true) ?>" >Next</a></td>
	        <td><a  href="<?php echo $this->getUrl('grid',null,['p'=>$pager->end],true) ?>" >End</a></td>
	    
	
		</tr>
	</table>
</div>